- name: Check if restart is required
  stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: Show if restart is required
  debug: msg="Reboot required" 
  when: reboot_required.stat.exists
